### ISSUE TITLE
Reboot project with boot 3.x

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-security-kerberos#165]
Everything in this project should get modernised including
- [x] #167
- [x] Setup build via gh actions
- [x] Base level to what boot 3.x brings
- [x] #166

**Comment by CoderYellow** [comment]
Glad to see this project is rebooted, I've done [some work](https://github.com/OpenProjectX/spring-security-kerberos) to upgrade to spring boot 2 and support for webflux. There wasn't too much code change, it is easy to migrate to spring boot 2. So do you have a plan to support spring boot 2 since the spring boot 3 is dependent on JDK 17 which could be a huge refactor, many users would rather stick to spring boot 2.
For the gradle config I just copied from [spring-security](https://github.com/spring-projects/spring-security). Why not combine this project to spring security as a sub module

**Comment by jvalkeal** [comment]
Current plan is to skip boot 2 and see how community takes it.

**Comment by Prutheus** [comment]
Is this already working with boot 3? When is a release of boot 3 compatibility planned?

**Comment by venkatnaveen7** [comment]
Looking for release with boot3
Can we take code from main branch ..?
Still its using javax
